[package]
name = "ubitix"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.28"
octocrab = "0.48.0"
regex = "1.12.2"
simplelog = "0.12.2"
